### ISSUE TITLE
Unhelpful exception when executing with no arguments

### ISSUE THREAD

**Issue by virtuald** [ned14/pcpp#16]
```
$ pcpp
Traceback (most recent call last):
  File "virtualenvs/frc/bin/pcpp", line 11, in <module>
    sys.exit(main())
  File "virtualenvs/frc/lib/python3.6/site-packages/pcpp/cmd.py", line 195, in main
    p = CmdPreprocessor(sys.argv)
  File "virtualenvs/frc/lib/python3.6/site-packages/pcpp/cmd.py", line 50, in __init__
    args = argp.parse_known_args(argv[1:])
  File "/usr/lib64/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.6/argparse.py", line 1975, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/usr/lib64/python3.6/argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "/usr/lib64/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "virtualenvs/frc/lib/python3.6/site-packages/pcpp/cmd.py", line 20, in __call__
    items += [argparse.FileType('rt')(value) for value in values]
  File "virtualenvs/frc/lib/python3.6/site-packages/pcpp/cmd.py", line 20, in <listcomp>
    items += [argparse.FileType('rt')(value) for value in values]
  File "/usr/lib64/python3.6/argparse.py", line 1187, in __call__
    self._errors)
TypeError: expected str, bytes or os.PathLike object, not _io.TextIOWrapper
```

* Python 3.6.6 linux
* pcpp 1.1.0
* ply 3.10

**Comment by ned14** [comment]
Wow, that's a bad bug. Thanks for reporting this!

**Comment by ned14** [comment]
Fixed. Thanks for reporting it!
