### ISSUE TITLE
Trying to use `pip install --no-use-pep517 --editable .`

### ISSUE THREAD

**Issue by CMCDragonkai** [ned14/pcpp#36]
It ends up failing:

```
    ERROR: Command errored out with exit status 1:
     command: /nix/store/zqr5sy6dxnas41s0axyhhvlqnhwj0ywk-python3-3.7.5/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/cmcdragonkai/Projects/pcpp/setup.py'"'"'; __file__='"'"'/home/cmcdragonkai/Projects/pcpp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /home/cmcdragonkai/Projects/pcpp/
    Complete output (8 lines):
    running egg_info
    creating pcpp.egg-info
    writing pcpp.egg-info/PKG-INFO
    writing dependency_links to pcpp.egg-info/dependency_links.txt
    writing entry points to pcpp.egg-info/entry_points.txt
    writing top-level names to pcpp.egg-info/top_level.txt
    writing manifest file 'pcpp.egg-info/SOURCES.txt'
    error: package directory 'pcpp/ply/ply' does not exist
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

I've got `ply` installed. When I didn't have `ply` installed, I also had this error:

```
    ERROR: Command errored out with exit status 1:
     command: /nix/store/zqr5sy6dxnas41s0axyhhvlqnhwj0ywk-python3-3.7.5/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/cmcdragonkai/Projects/pcpp/setup.py'"'"'; __file__='"'"'/home/cmcdragonkai/Projects/pcpp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /home/cmcdragonkai/Projects/pcpp/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/cmcdragonkai/Projects/pcpp/setup.py", line 4, in <module>
        import os, pcpp
      File "/home/cmcdragonkai/Projects/pcpp/pcpp/__init__.py", line 1, in <module>
        from .pcmd import main, version, CmdPreprocessor
      File "/home/cmcdragonkai/Projects/pcpp/pcpp/pcmd.py", line 5, in <module>
        from pcpp.preprocessor import Preprocessor, OutputDirective, Action
      File "/home/cmcdragonkai/Projects/pcpp/pcpp/preprocessor.py", line 161, in <module>
        from ply import lex
    ModuleNotFoundError: No module named 'ply'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Note that I'm inside `nix-shell` via NixOS.

**Comment by CMCDragonkai** [comment]
Ok I just realized that's cause I'm missing the submodule.
