### ISSUE TITLE
README.rst isn't included in the pip package.

### ISSUE THREAD

**Issue by ntisserand** [ned14/pcpp#4]
I am using Python 2.7.13 on Windows.

   pip install pcpp

```
Collecting pcpp
  Using cached pcpp-1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\nt\appdata\local\temp\pip-build-xdykv7\pcpp\setup.py", line 9, in <module>
        with open(os.path.join(here, 'Readme.rst')) as f:
    IOError: [Errno 2] No such file or directory: 'c:\\users\\nt\\appdata\\local\\temp\\pip-build-xdykv7\\pcpp\\Readme.rst'
```

**Comment by ntisserand** [comment]
See also: https://github.com/ned14/pcpp/pull/5

**Comment by ned14** [comment]
Fixed
