### ISSUE TITLE
ply package is not defined as a requirement - pip install fails

### ISSUE THREAD

**Issue by mbdevpl** [ned14/pcpp#6]
```
$ pip3.6 install pcpp
Collecting pcpp
  Downloading pcpp-1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/t1/pg0pff894b32wl4q8kcsgmv00000gn/T/pip-build-p4kyoyeh/pcpp/setup.py", line 4, in <module>
        import os, pcpp
      File "/private/var/folders/t1/pg0pff894b32wl4q8kcsgmv00000gn/T/pip-build-p4kyoyeh/pcpp/pcpp/__init__.py", line 1, in <module>
        from .cmd import main, version
      File "/private/var/folders/t1/pg0pff894b32wl4q8kcsgmv00000gn/T/pip-build-p4kyoyeh/pcpp/pcpp/cmd.py", line 5, in <module>
        from pcpp.preprocessor import Preprocessor, OutputDirective
      File "/private/var/folders/t1/pg0pff894b32wl4q8kcsgmv00000gn/T/pip-build-p4kyoyeh/pcpp/pcpp/preprocessor.py", line 95, in <module>
        from ply.lex import LexToken
    ModuleNotFoundError: No module named 'ply'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/t1/pg0pff894b32wl4q8kcsgmv00000gn/T/pip-build-p4kyoyeh/pcpp/
```
Currently user has to manually install ply package and rerun the pcpp install. Which fails anyway due to #4 ...

**Comment by mbdevpl** [comment]
As a crappy workaround: `pip3.6 install git+https://github.com/ned14/pcpp.git`

**Comment by ned14** [comment]
Fixed!
