### ISSUE TITLE
Macro line continuation bug

### ISSUE THREAD

**Issue by dslijepcevic** [ned14/pcpp#63]
`test.c`:
```c
#define x\
 \

#include "test.h"
```

`test.h`:
```c
int f();
```

Running `pcpp --line-directive= --passthru-defines test.c` produces the following output:
```c
#define x int f();
```

If I omit the leading space on the second line of `#define x` then I get:
```
Traceback (most recent call last):
  File "/home/dux/.local/lib/python2.7/site-packages/pcpp/pcmd.py", line 140, in __init__
    self.write(self.args.output)
  File "/home/dux/.local/lib/python2.7/site-packages/pcpp/preprocessor.py", line 1341, in write
    toks[n-1].value = toks[n-1].value[0]
IndexError: string index out of range
None

INTERNAL PREPROCESSOR ERROR AT AROUND test.c:3, FATALLY EXITING NOW
```

**Comment by ned14** [comment]
Confirmed.

**Comment by ned14** [comment]
Fixed. Let me know if it isn't fixed for you. Thanks for reporting the issue!
